services:
  floci:
    image: floci/floci:latest
    container_name: floci-emulator
    ports:
      - "4566:4566"
    environment:
      FLOCI_STORAGE_MODE: memory
      FLOCI_DEFAULT_REGION: us-east-1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
